### ISSUE TITLE
Maximum 200,000 entries exceeded for unified adware + malware list

### ISSUE THREAD

**Issue by damoclark** [tastapod/snitcher#4]
Hi Daniel,

Thanks for sharing your work on snitcher.  

I attempted to subscribe to the [unified (adware + malware)](https://rules.snitcher.dannorth.net/unified.lsrules) rule group file, but Little Snitch is complaining that the list exceeds the maximum number of entries:

```
Too many rules, hostnames or domains in rule group (exceeded the allowed maximum of 200,000 entries).
```

A quick `wc -l` of the rule file shows 207,985.  A rather depressing statistic for ad and malware, but unsurprising.

Is it possible to update the build script for generating the rules to split rule groups into multiple files of maximum 200,000 entries?  The downside is being unaware that the number of rule groups might again spill over to three, but at least its still possible to keep the rules up to date.

The only other possible solution I can see is to add some logic that condenses groups of hosts into a single subdomain rule, if that is supported in the group rules format.  Much more work, and error prone no doubt.

What do you think Daniel?

Cheers,
Damo.

**Comment by tastapod** [comment]
Hi Damo,

Thanks for submitting this. I noticed mine had stopped updating but I hadn't got to looking at it yet.

I think the easiest thing is to get the build script to split each list into chunks of 200,000 entries and update the static web page to show something like:

- Unified (Adware + Malware)
  - Part 1 `subscribe`, `rule group file`
  - Part 2 `subscribe`, `rule group file`
...

I will make it a breaking change, so that e.g. `unified` -> `unified-1` and `unified-2`, and put an explainer notice on the web page. That way people won't continue subscribing to just the first 200k entries of a list and thinking they have the whole list.

WDYT?

**Comment by damoclark** [comment]
Hey Daniel, yes that makes sense to me. 👍
