### ISSUE TITLE
File does not exists

### ISSUE THREAD

**Issue by adoreparler** [tastapod/snitcher#5]
https://rules.snitcher.dannorth.net/unified-01.lsrules

this file does not exist

**Comment by tastapod** [comment]
It looks like Steven Black has culled a lot of false positives from his lists, and most of them are back below 200,000.

![](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts_file_size_history.png)

Snitcher only generates the second file if there are more than 200k entries. I could change it to split each list in half, rather than at 200k, so there will always be two files. WDTY?

**Comment by adoreparler** [comment]
I am fine with one file, just wanted to make sure I was not missing any :)

**Comment by tastapod** [comment]
I think it is less "surprising" to always have two files! I made the change so it creates two equal-sized lists, which is easier for LittleSnitch to consume in any case.
